apiVersion: v1
kind: Pod
metadata:
  name: nicepod
  labels:
    app: nginx
  annotations:
    author: me
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP