apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-world
              image: centos:7
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - echo Hello World
          restartPolicy: OnFailure
