name: Validate Shell scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Validate-Shell:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: Install shfmt
        run: sudo apt-get install shfmt -y
      - name: Run shfmt
        run: shfmt -d .
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
